### ISSUE TITLE
有一点问题

### ISSUE THREAD

**Issue by TatleCat** [Slime00/bilibili-live-monitor#2]
![Screenshot_20230419_210111](https://user-images.githubusercontent.com/128877938/233086428-8f6035a8-9cb0-435b-830a-5b7e6bfa31f1.jpg)
直播时间显示不准确
另外,如果把结束语删掉
日志里会持续输出这个
![Screenshot_20230419_210919](https://user-images.githubusercontent.com/128877938/233086798-d3549752-b2b2-430a-94d2-59bc20c05d4c.jpg)
时间长会让koishi崩掉
也希望能支持修改
或是否启用这个下播提示与持续时间

**Comment by Slime00** [comment]
问题1暂未找到复现成功

**Comment by Slime00** [comment]
问题2 已经删除无用log 开发环境调试用忘记删除,生产环境不需要这些信息
